title: Flow Client Library (FCL) Protocol Specification
description: The Flow Client Library (FCL) Protocol Specification defines the communication protocol which connects dApps to wallets on the Flow blockchain.
theme: just-the-docs

url: https://just-the-docs.github.io

markdown: kramdown
highlighter: rouge

timezone: America/Vancouver